# Generated by Django 3.0.7 on 2020-06-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('TermId', models.AutoField(primary_key=True, serialize=False)),
                ('TermName', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Term',
            },
        ),
    ]
