# Generated by Django 3.0.7 on 2020-06-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
