# Generated by Django 3.0.7 on 2020-06-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('StudNo', models.CharField(max_length=45)),
                ('StudName', models.CharField(max_length=45)),
                ('Term', models.CharField(max_length=45)),
                ('Course', models.CharField(max_length=45)),
                ('RefName', models.CharField(max_length=45)),
                ('Username', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
    ]
