# Generated by Django 3.0.7 on 2020-06-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentinfo',
            table='studinfo',
        ),
    ]
