# Generated by Django 3.0.7 on 2020-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgnt', '0002_auto_20200628_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AdminNo', models.CharField(max_length=45)),
                ('AdminName', models.CharField(max_length=45)),
                ('Term', models.CharField(max_length=45)),
                ('Course', models.CharField(max_length=45)),
                ('Username', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table=None,
        ),
    ]
