# Generated by Django 3.0.7 on 2020-07-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0003_auto_20200713_1713'),
        ('usermgnt', '0003_auto_20200713_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='StudID',
        ),
        migrations.CreateModel(
            name='MyAttendance',
            fields=[
                ('myattendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('studnum', models.ForeignKey(db_column='studetails', on_delete=django.db.models.deletion.CASCADE, to='rollcallmodule.attendancerec')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
